CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE SCHEMA IF NOT EXISTS auth_schema;
CREATE SCHEMA IF NOT EXISTS profile_schema;
CREATE SCHEMA IF NOT EXISTS job_schema;
CREATE SCHEMA IF NOT EXISTS skill_schema;
CREATE SCHEMA IF NOT EXISTS applying_schema;
CREATE SCHEMA IF NOT EXISTS cv_schema;
CREATE SCHEMA IF NOT EXISTS message_schema;
CREATE SCHEMA IF NOT EXISTS matching_schema;
CREATE SCHEMA IF NOT EXISTS candidate_schema;
CREATE SCHEMA IF NOT EXISTS recruitment_schema;
